from .context_managers import settings as settings
from fabric import tasks as tasks
from typing import Any

def task(*args, **kwargs): ...
def hosts(*host_list): ...
def roles(*role_list): ...
def runs_once(func): ...
def serial(func): ...
def parallel(pool_size: Any | None = ...): ...
def with_settings(*arg_settings, **kw_settings): ...
