from fabric.context_managers import settings as settings
#from fabric.network import ssh as ssh

class JobQueue:
    def __init__(self, max_running, comms_queue) -> None: ...
    def __len__(self): ...
    def close(self) -> None: ...
    def append(self, process) -> None: ...
    def run(self): ...

# This is sample code, not really something that gets exposed to the API
#def try_using(parallel_type) -> None: ...
