from collections.abc import Generator
from fabric.context_managers import settings as settings
from fabric.state import connections as connections, env as env, output as output, win32 as win32
from fabric.utils import warn as warn
from typing import Any

class SFTP:
    ftp: Any
    def __init__(self, host_string) -> None: ...
    def __getattr__(self, attr): ...
    def isdir(self, path): ...
    def islink(self, path): ...
    def exists(self, path): ...
    def glob(self, path): ...
    def walk(self, top, topdown: bool = ..., onerror: Any | None = ..., followlinks: bool = ...) -> Generator[Any, None, None]: ...
    def mkdir(self, path, use_sudo) -> None: ...
    def get(self, remote_path, local_path, use_sudo, local_is_path, rremote: Any | None = ..., temp_dir: str = ...): ...
    def get_dir(self, remote_path, local_path, use_sudo, temp_dir): ...
    def put(self, local_path, remote_path, use_sudo, mirror_local_mode, mode, local_is_path, temp_dir: str = ...): ...
    def put_dir(self, local_path, remote_path, use_sudo, mirror_local_mode, mode, temp_dir): ...
