from fabric import state as state
from fabric.utils import abort as abort, indent as indent

class _Dict(dict): ...

def crawl(name, mapping): ...
def merge(hosts, roles, exclude, roledefs): ...
def parse_kwargs(kwargs): ...
