pull_request_rules:
  - name: backport to master
    conditions:
      - merged
      - base=main
      - milestone=1.13.x
      - label="Please Backport"
    actions:
      backport:
        branches:
          - 1.13.x
        ignore_conflicts: True
        label_conflicts: "bp-conflict"
      label:
        add: [Backported]

  - name: label Mergify backport PR
    conditions:
      - body~=This is an automated backport of pull request \#\d+ done by Mergify
    actions:
      label:
        add: [Backport]
