version: 2

build:
    os: ubuntu-20.04
    tools:
        python: "3.6"

formats: all

sphinx:
  configuration: docs/conf.py

submodules:
   exclude: all

python:
   install:
      - requirements: docs/requirements.txt
