version: 2

build:
    os: ubuntu-20.04
    tools:
        python: "mambaforge-4.10"

sphinx:
  configuration: docs/conf.py

submodules:
   exclude: all

conda:
   environment: conda-reqs/docs.yaml

formats:
   - pdf
   - htmlzip
   - epub

