name: change-workflow-instance-states
description: "Changes the state of all instances associated with the current workflow."

inputs:
  new-state:
    description: "The state the workflow instances should adopt."
    required: true
  github-token:
    description: "Personal Access Token on GitHub with workflow access"
    required: true
  platform:
    description: "The platform on which CI is running."
    default: 'aws'

runs:
  using: "composite"
  steps:
      - uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
      - run: .github/scripts/change-workflow-instance-states.py ${{ inputs.platform }} ${{ github.run_id }} ${{ inputs.new-state }} ${{ inputs.github-token }}
        shell: bash
