#!/bin/sh
#
# Start the network....
#

# Debian ifupdown needs the /run/network lock directory
mkdir -p /run/network

case "$1" in
  start)
	printf "Starting network: "
#    ifconfig eth0 hw ether 00:12:6D:00:00:07
	/sbin/ifup -a
    ip link set eth0 up
    mac=$(ifconfig | grep -o "..:..:..:..:..:..")
    machigh=$(echo $mac | cut -c 13-14 -)
    maclow=$(echo $mac | cut -c 16-17 -)
    ip addr add 192.168.$((16#$machigh)).$((16#$maclow))/24 dev eth0
#	/sbin/ifup eth0
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  stop)
	printf "Stopping network: "
	/sbin/ifdown -a
#	/sbin/ifdown eth0
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

