name: repo-setup-aws
description: "Runs all baseline setup to interact with a AWS-hosted manager instance"

runs:
  using: "composite"
  steps:
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ env.FIRESIM_PEM }}
          known_hosts: unnecessary
