name: Bug Report
description: File a bug report
labels: ["bug"]
body:
  - type: checkboxes
    attributes:
      label: Background Work
      description: Yes, I searched the following areas for a prior solution.
      options:
        - label: Yes, I searched the [mailing list](https://groups.google.com/forum/#!forum/firesim)
          required: true
        - label: Yes, I searched [prior issues](https://github.com/firesim/firesim/issues)
          required: true
        - label: Yes, I searched the [documentation](https://docs.fires.im/en/stable/)
          required: true

  - type: textarea
    attributes:
      label: FireSim Version and Hash
      description: Repository version for reproducibility
      placeholder: Version + Hash
      value: |
        <!-- copy/paste the output of `git describe --tags --long` below -->
        
    validations:
      required: true

  - type: textarea
    attributes:
      label: OS Setup
      description: OS setup for reproducibility
      placeholder: OS information
      value: |
        ```
        <!-- copy/paste the output of `uname -a; lsb_release -a` below -->
        ```
    validations:
      required: true

  - type: textarea
    attributes:
      label: Other Setup
      description: Any other setup relevant
      placeholder: Other setup
      value: |
        <!-- Ex: Prior steps taken / Documentation Followed / etc... -->
    validations:
      required: false

  - type: textarea
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Other Information
      description: Other information needed to reproduce the issue.
      placeholder: |
        Detailed explanations
        Stack traces
        Log files. Tip - You can add images / log files by clicking this area to highlight it and then dragging files in
        Related issues
        Suggestions on fixes
        Other links
    validations:
      required: false
