//See LICENSE for license details.

package firesim.midasexamples

import java.io.File
import freechips.rocketchip.config.Config
import org.scalatest.Suites

import firesim.TestSuiteUtil._
import firesim.BasePlatformConfig

abstract class PrintfSuite(
  targetName:         String,
  targetConfigs:      String                  = "NoConfig",
  platformConfigs:    Seq[Class[_ <: Config]] = Seq(),
  basePlatformConfig: BasePlatformConfig      = BaseConfigs.F1,
  simulationArgs:     Seq[String]             = Seq(),
) extends TutorialSuite(targetName, targetConfigs, platformConfigs, basePlatformConfig, simulationArgs) {

  /** Check that we are extracting from the desired ROI by checking that the bridge-inserted cycle prefix matches the
    * target-side cycle prefix
    */
  def checkPrintCycles(filename: String, startCycle: Int, endCycle: Int, linesPerCycle: Int) {
    it should "have synthesized printfs in the desired cycles" in {
      val synthLogFile     = new File(genDir, s"/${filename}")
      val synthPrintOutput = extractLines(synthLogFile, prefix = "")
      val length           = synthPrintOutput.size
      assert(length == linesPerCycle * (endCycle - startCycle + 1))
      for ((line, idx) <- synthPrintOutput.zipWithIndex) {
        val currentCycle = idx / linesPerCycle + startCycle
        val printRegex   = raw"^CYCLE:\s*(\d*) SYNTHESIZED_PRINT CYCLE:\s*(\d*).*".r
        line match {
          case printRegex(cycleA, cycleB) =>
            assert(cycleA.toInt == currentCycle)
            assert(cycleB.toInt == currentCycle)
        }
      }
    }
  }

  // Checks that a bridge generated log in ${genDir}/${synthLog} matches output
  // generated directly by the RTL simulator (usually with printfs)
  def diffSynthesizedLog(
    synthLog:         String,
    stdoutPrefix:     String = "SYNTHESIZED_PRINT ",
    synthPrefix:      String = "SYNTHESIZED_PRINT ",
    synthLinesToDrop: Int    = 0,
  ) {
    behavior.of(s"${synthLog}")
    it should "match the prints generated by the verilated design" in {
      val verilatedLogFile = new File(outDir, s"/${targetName}.${backendSimulator}.out")
      val synthLogFile     = new File(genDir, s"/${synthLog}")
      val verilatedOutput  = extractLines(verilatedLogFile, stdoutPrefix).sorted
      val synthPrintOutput = extractLines(synthLogFile, synthPrefix, synthLinesToDrop).sorted
      diffLines(verilatedOutput, synthPrintOutput)
    }
  }

  def assertSynthesizedLogEmpty(synthLog: String) {
    s"${synthLog}" should "be empty" in {
      val synthLogFile = new File(genDir, s"/${synthLog}")
      val lines        = extractLines(synthLogFile, prefix = "")
      assert(lines.isEmpty)
    }
  }
}

abstract class PrintModuleTest(val platform: BasePlatformConfig)
    extends PrintfSuite(
      "PrintfModule",
      simulationArgs     = Seq("+print-no-cycle-prefix", "+print-file=synthprinttest.out"),
      basePlatformConfig = platform,
    ) {
  runTest("vcs", true)
  diffSynthesizedLog("synthprinttest.out0")
}

class PrintfModuleF1Test    extends PrintModuleTest(BaseConfigs.F1)
class PrintfModuleVitisTest extends PrintModuleTest(BaseConfigs.Vitis)

abstract class NarrowPrintfModuleTest(val platform: BasePlatformConfig)
    extends PrintfSuite(
      "NarrowPrintfModule",
      simulationArgs     = Seq("+print-no-cycle-prefix", "+print-file=synthprinttest.out"),
      basePlatformConfig = platform,
    ) {
  diffSynthesizedLog("synthprinttest.out0")
}

class NarrowPrintfModuleF1Test    extends NarrowPrintfModuleTest(BaseConfigs.F1)
class NarrowPrintfModuleVitisTest extends NarrowPrintfModuleTest(BaseConfigs.Vitis)

abstract class MulticlockPrintfModuleTest(val platform: BasePlatformConfig)
    extends PrintfSuite(
      "MulticlockPrintfModule",
      simulationArgs     = Seq("+print-file=synthprinttest.out", "+print-no-cycle-prefix"),
      basePlatformConfig = platform,
    ) {
  diffSynthesizedLog("synthprinttest.out0")
  diffSynthesizedLog(
    "synthprinttest.out1",
    stdoutPrefix         = "SYNTHESIZED_PRINT_HALFRATE ",
    synthPrefix          = "SYNTHESIZED_PRINT_HALFRATE ",
    // Corresponds to a single cycle of extra output.
    synthLinesToDrop     = 4,
  )
}

class MulticlockPrintF1Test    extends MulticlockPrintfModuleTest(BaseConfigs.F1)
class MulticlockPrintVitisTest extends MulticlockPrintfModuleTest(BaseConfigs.Vitis)

class PrintfCycleBoundsF1Test extends PrintfCycleBoundsTestBase(startCycle = 172, endCycle = 9377)

class TriggerPredicatedPrintfF1Test
    extends PrintfSuite("TriggerPredicatedPrintf", simulationArgs = Seq("+print-file=synthprinttest.out"))
    with TriggerPredicatedPrintfConsts {
  val startCycle = assertTriggerCycle + 2
  val endCycle = deassertTriggerCycle + 2
  checkPrintCycles("synthprinttest.out0", startCycle, endCycle, linesPerCycle = 2)
}

class PrintfCycleBoundsTestBase(startCycle: Int, endCycle: Int)
    extends PrintfSuite(
      "PrintfModule",
      simulationArgs                                                          = Seq(
        "+print-file=synthprinttest.out",
        s"+print-start=${startCycle}",
        s"+print-end=${endCycle}",
      ),
    ) {
  checkPrintCycles("synthprinttest.out0", startCycle, endCycle, linesPerCycle = 4)
}

class PrintfGlobalResetConditionTest
    extends PrintfSuite(
      "PrintfGlobalResetCondition",
      simulationArgs = Seq("+print-no-cycle-prefix", "+print-file=synthprinttest.out"),
    ) {
  // The log should be empty.
  assertSynthesizedLogEmpty("synthprinttest.out0")
  assertSynthesizedLogEmpty("synthprinttest.out1")
}

class AutoCounterPrintfF1Test
    extends PrintfSuite(
      "AutoCounterPrintfModule",
      simulationArgs                                     = Seq("+print-file=synthprinttest.out"),
      platformConfigs                                    = Seq(classOf[AutoCounterPrintf]),
    ) {
  diffSynthesizedLog("synthprinttest.out0", stdoutPrefix = "AUTOCOUNTER_PRINT CYCLE", synthPrefix = "CYCLE")
}

class PrintfSynthesisCITests
    extends Suites(
      new PrintfModuleF1Test,
      new PrintfModuleVitisTest,
      new NarrowPrintfModuleF1Test,
      new MulticlockPrintF1Test,
      new PrintfCycleBoundsF1Test,
      new TriggerPredicatedPrintfF1Test,
      new PrintfGlobalResetConditionTest,
      new AutoCounterPrintfF1Test,
    )
