from typing import Any

def rsync_project(remote_dir, local_dir: Any | None = ..., exclude=..., delete: bool = ..., extra_opts: str = ..., ssh_opts: str = ..., capture: bool = ..., upload: bool = ..., default_opts: str = ...): ...
def upload_project(local_dir: Any | None = ..., remote_dir: str = ..., use_sudo: bool = ...) -> None: ...
