# With the job-end action, this provides the machinery to skip running jobs
# that have previously passed. This is not supported on EC2-manager hosted
# jobs, where all related jobs must be re-run when restarting the workflow (since the
# previous spot-instance manager is terminated on a failure)

name: job-start
description: "Setup a job status"
outputs:
  run_result:
    value: ${{ steps.run_result.outputs.run_result }}

runs:
  using: "composite"
  steps:
    - name: Restore the previous run result
      uses: actions/cache@v2
      with:
        path: run_result
        key: ${{ github.run_id }}-${{ github.job }}
        restore-keys: ${{ github.run_id }}-${{ github.job }}
    - name: Set run_result to default or use cached value
      id: run_result
      run: echo "run_result=$(cat run_result 2>/dev/null || echo 'default')" >> $GITHUB_OUTPUT
      shell: bash
