#!/bin/busybox sh

/bin/busybox --install -s

# Load platform drivers
sh /loadDrivers.sh

if [ $? != 0 ]; then
  echo "Failed to load drivers. Dropping into an emergency shell"
  exec /bin/busybox sh
fi

# Mount the /proc and /sys filesystems.
mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs none /dev

if [ -e /dev/generic-blkdev ]; then
  mount -o ro /dev/generic-blkdev /mnt/root
elif [ -e /dev/vda ]; then
  mount -o ro /dev/vda /mnt/root
else
  echo "Failed to load an appropriate block device. Dropping into emergency shell:"
  exec /bin/busybox sh
fi

exec switch_root /mnt/root /sbin/init

echo "Failed to find appropriate init"
exec /bin/busybox sh
